version: '3.1'
services:
  db:
    image: mysql
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3307:3307"
    volumes:
      - angularspring_users:/var/lib/mysql

volumes:
  angularspring_users: